config/routes.rb
Rails.application.routes.draw do
  # Devise for developers
  devise_for :developers, controllers: {registrations: "developers/registrations"}

  # Root route
  root to: "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  # Resources
  resources :labels
  resources :developer_projects
  resources :notifications

  # Projects
  resources :projects do
    resources :tasks do
      member do
        patch "start"
        patch "finish"
      end
    end
    member do
      patch "cancel"
      patch "start"
      patch "finish"
    end
  end

  # Tasks
  resources :tasks do
    member do
      post "add_label"
      delete "remove_label"
      post "add_developer"
      delete "remove_developer"
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  has_many :developer_tasks, dependent: :destroy
  has_many :developers, through: :developer_tasks
  has_many :tasks_labels, dependent: :destroy
  has_many :labels, through: :tasks_labels

  validates :description,
    presence: true
  validates :title,
    presence: true
  validates :task_type,
    presence: true,
    inclusion: {in: %w[Feature Chore Bug Release], message: "%{value} is not a valid task type"}
  validates :status,
    presence: true,
    inclusion: {in: %w[Unstarted Started Finished], message: "%{value} is not a valid status"}
  validates :priority,
    inclusion: {in: %w[Low Medium High], message: "%{value} is not a valid priority"}
  validate :start_date_cannot_be_in_the_past, :end_date_cannot_be_in_the_past, :end_date_has_to_be_greater_than_start_date

  def start_date_cannot_be_in_the_past
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "can't be in the past")
    end
  end

  def end_date_cannot_be_in_the_past
    if end_date.present? && end_date < Date.today
      errors.add(:end_date, "can't be in the past")
    end
  end

  def end_date_has_to_be_greater_than_start_date
    if start_date.present? && end_date.present? && start_date > end_date
      errors.add(:end_date, "can't be earlier than start date")
    end
  end

  scope :feature, -> { where(task_type: "Feature") }
  scope :chore, -> { where(task_type: "Chore") }
  scope :bug, -> { where(task_type: "Bug") }
  scope :release, -> { where(task_type: "Release") }

  scope :unstarted, -> { where(status: "Unstarted") }
  scope :started, -> { where(status: "Started") }
  scope :finished, -> { where(status: "Finished") }

  scope :low, -> { where(priority: "Low") }
  scope :medium, -> { where(priority: "Medium") }
  scope :high, -> { where(priority: "High") }

  scope :recent, ->(*args) {
                   where("start_date > ?",
                     (args.first || 2.weeks.ago))
                 }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project, only: [:new, :create, :show, :edit, :update, :destroy, :index, :start, :finish]
  before_action :set_task, only: [:show, :edit, :update, :destroy, :start, :finish]

  # GET /tasks or /tasks.json
  def index
    @tasks = @project.tasks
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET projects/tasks/new
  def new
    @task = @project.tasks.build
  end

  # GET /tasks/1/edit
  def edit
    @available_labels = Label.where.not(id: @task.labels.ids)
    @available_developers = @project.developer_projects.where(status: "Active").where.not(developer_id: @task.developer_tasks.pluck(:developer_id)).map(&:developer)
  end

  # POST /tasks or /tasks.json
  def create
    @task = @project.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_task_url(@project, @task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, alert: "Unprocessable entity. Errors: #{@task.errors.full_messages.join(", ")}", status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_task_url(@project, @task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.developer_tasks.each do |developer_task|
      developer_task.developer.notifications.create(text: "The task #{@task.title} of project #{@project.title} has been deleted.", read: false)
    end

    @task.destroy

    respond_to do |format|
      format.html { redirect_to project_tasks_path(@project), notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_developer
    @task = Task.find(params[:id])
    developer = Developer.find(params[:developer_id])
    unless @task.developers.include?(developer)
      @task.developers << developer
      notification = developer.notifications.build(text: "You have been assigned to the task " + @task.title + " of project " + @task.project.title, read: false)
      if notification.save
        puts "Notification created. To #{developer.email}: #{notification.text}"
      else
        puts notification.errors.full_messages
      end
    end

    respond_to do |format|
      if @task.save
        format.html { redirect_to edit_project_task_path(@task.project, @task), notice: "Owner was successfully added." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :show, alert: "Unprocessable entity. Errors: #{@task.errors.full_messages.join(", ")}", status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove_developer
    @task = Task.find(params[:id])
    developer = Developer.find(params[:developer_id])
    @task.developers.delete(developer)
    notification = developer.notifications.build(text: "You have been removed from the task " + @task.title + " of project " + @task.project.title, read: false)
    if notification.save
      puts "Notification created. To #{developer.email}: #{notification.text}"
    else
      puts notification.errors.full_messages
    end

    respond_to do |format|
      format.html { redirect_to edit_project_task_path(@task.project, @task), notice: "Owner was successfully removed." }
      format.json { head :no_content }
    end
  end

  def add_label
    @task = Task.find(params[:id])
    label = Label.find(params[:label_id])
    @task.labels << label unless @task.labels.include?(label)

    respond_to do |format|
      if @task.save
        format.html { redirect_to edit_project_task_path(@task.project, @task), notice: "Label was successfully added." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :show, alert: "Unprocessable entity. Errors: #{@task.errors.full_messages.join(", ")}", status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove_label
    @task = Task.find(params[:id])
    label = Label.find(params[:label_id])
    if @task.labels.include?(label)
      @task.labels.delete(label)
    end

    respond_to do |format|
      format.html { redirect_to edit_project_task_path(@task.project, @task), notice: "Label was successfully removed." }
      format.json { head :no_content }
    end
  end

  def start
    respond_to do |format|
      if @task.update(status: "Started", start_date: Date.today, end_date: nil)
        format.html { redirect_to project_tasks_path(@project), notice: "Task was successfully started." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :show, alert: "Unprocessable entity. Errors: #{task.errors.full_messages.join(", ")}", status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def finish
    respond_to do |format|
      if @task.update(status: "Finished", end_date: Date.today)
        @task.developer_tasks.each do |developer_task|
          developer_task.developer.notifications.create(text: "The task #{@task.title} of project #{@project.title} has been finished.", read: false)
        end
        format.html { redirect_to project_tasks_path(@project), notice: "Task was successfully finished." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :show, alert: "Unprocessable entity. Errors: #{@task.errors.full_messages.join(", ")}", status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = @project.tasks.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:start_date, :end_date, :status, :description, :task_type, :estimation, :priority, :title)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_add_developer_form.html.erb
  <%= form_with(url: add_developer_task_path(task), method: :post) do |form| %>
  <div class="row mb-2">
    <%= form.label :developer_id, "Add Developer", class: "col-sm-3 col-form-label" %>
    <div class="col-sm-9">
      <%= form.select :developer_id, @available_developers.collect { |d| [d.name + ' ' + d.lastname + ' (' + d.email + ')', d.id] }, { include_blank: true }, class: "form-select" %>
    </div>
  </div>
  <%= form.submit "Add", class: "btn btn-primary" %>
<% end %>

app/views/tasks/_add_label_form.html.erb
<%= form_with(url: add_label_task_path(task), method: :post) do |form| %>
  <div class="row mb-2">
    <%= form.label :label_id, "Add Label", class: "col-sm-3 col-form-label" %>
    <div class="col-sm-9">
      <%= form.select :label_id, options_for_select(@available_labels.collect { |label| [label.name, label.id] }), { include_blank: true }, {class: "form-select"} %>
    </div>
  </div>
  <%= form.submit "Add", class: "btn btn-primary" %>
<% end %>

app/views/tasks/_developers_list.html.erb
<% task.developers.each do |developer| %>
  <div>
    <ul>
      <li>
        <div class="row">
          <div class="col-6">
            <%= developer.name %> <%= developer.lastname %>
          </div>
          <div class="col-4">
            <%= form_with(url: remove_developer_task_path(task, developer_id: developer.id), method: :delete, local: true) do %>
              <button type="submit" class="btn btn-sm btn-danger ms-2">
                <i class="bi bi-trash"></i>
              </button>
            <% end %>
          </div>
        </div>
      </li>
    </ul>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<div class="card-body">
  <%= form_with(model: [@project, task]) do |form| %>
    <% if task.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>
        <ul>
          <% task.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row mb-2">
      <%= form.label :title, "Title *", class: "col-sm-3 col-form-label" %>
      <div class="col-sm-9">
        <%= form.text_field :title, class: "form-control", required: true %>
      </div>
    </div>
    <div class="row mb-2">
      <%= form.label :start_date, class: "col-sm-3 col-form-label" %>
      <div class="col-sm-9">
        <%= form.date_field :start_date, class: "form-control" %>
      </div>
    </div>
    <div class="row mb-2">
      <%= form.label :end_date, class: "col-sm-3 col-form-label" %>
      <div class="col-sm-9">
        <%= form.date_field :end_date, class:"form-control" %>
      </div>
    </div>
    <div class="row mb-2">
      <%= form.label :status, "Status *", class: "col-sm-3 col-form-label"%>
      <div class="col-sm-9">
        <%= form.select :status, ['Unstarted', 'Started', 'Finished'], {}, class: "form-select", required: true %>
      </div>
    </div>
    <div class="row mb-2">
      <%= form.label :description, "Description *", class: "col-sm-3 col-form-label" %>
      <div class="col-sm-9">
        <%= form.text_area :description, class: "form-control", required: true, rows: 10 %>
      </div>
    </div>
    <div class="row mb-2">
      <%= form.label :task_type, "Type *", class: "col-sm-3 col-form-label" %>
      <div class="col-sm-9">
        <%= form.select :task_type, ['Feature', 'Chore', 'Bug', 'Release'], {}, class: "form-select", required: true %>
      </div>
    </div>
    <div class="row mb-2">
      <%= form.label :estimation, class: "col-sm-3 col-form-label" %>
      <div class="col-sm-9">
        <%= form.number_field :estimation, class: "form-control" %>
      </div>
    </div>
    <div class="row mb-2">
      <%= form.label :priority, "Priority *", class: "col-sm-3 col-form-label" %>
      <div class="col-sm-9">
        <%= form.select :priority, ['Low', 'Medium', 'High'], {}, class: "form-select", required: true %>
      </div>
    </div>
    <div class="d-flex justify-content-between">
      <%= link_to "Cancel", project_tasks_path(@project), class: "btn btn-danger" %>
      <%= form.submit class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/tasks/_labels_list.html.erb
<% task.labels.each do |label| %>
  <div>
    <ul>
      <li>
        <div class="row">
          <div class="col-6">
            <%= label.name %>
          </div>
          <div class="col-4">
            <%= form_with(url: remove_label_task_path(task, label_id: label.id), method: :delete, local: true) do %>
              <button type="submit" class="btn btn-sm btn-danger ms-2">
                <i class="bi bi-trash"></i>
              </button>
            <% end %>
          </div>
        </div>
      </li>
    </ul>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<% if local_assigns[:view_context] == 'index' %>
  <div id="<%= dom_id task %>", class="card" style="margin-bottom: 1rem;">
<% elsif local_assigns[:view_context] == 'show' %>
  <div id="<%= dom_id task %>">
<% end %>
    <div class="card-header">
      <h4>
        <%= task.title %>
      </h4>
    </div>
    <div class="card-body">
      <p class="card-text">
        <strong>Start date:</strong>
        <%= task.start_date %>
      </p>
      <p class="card-text">
        <strong>End date:</strong>
        <%= task.end_date %>
      </p>
      <p class="card-text">
        <strong>Status:</strong>
        <%= task.status %>
      </p>
      <p class="card-text">
        <strong>Description:</strong>
        <% if local_assigns[:view_context] == 'index' %>
          <div class="card" style="height: 5rem; overflow: auto;">
            <p style="margin: 5px;"><%= task.description %></p>
          </div>
        <% elsif local_assigns[:view_context] == 'show' %>
          <div class="card">
            <p style="margin: 5px;"><%= task.description %></p>
          </div>
        <% end %>
      </p>
      <p class="card-text">
        <strong>Type:</strong>
        <%= task.task_type %>
      </p>
      <p class="card-text">
        <strong>Estimation:</strong>
        <%= task.estimation %>
      </p>
      <p class="card-text">
        <strong>Priority:</strong>
        <%= task.priority %>
      </p>
      <p class="card-text">
        <strong>Owners:</strong>
        <% task.developers.each do |developer| %>
          <ul>
            <li><%= developer.name %> <%= developer.lastname %></li>
          </ul>
        <% end %>
      </p>
      <p class="card-text">
        <strong>Labels:</strong>
        <% task.labels.each do |label| %>
          <ul>
            <li><%= label.name %></li>
          </ul>
        <% end %>
      </p>
      <div class="d-flex justify-content-between">
        <% if local_assigns[:view_context] == 'index' %>
          <%= link_to "Show", project_task_path(@project, task), class: "btn btn-outline-primary" %>
        <% end %>
        <%= link_to "Edit", edit_project_task_path(@project, task), class: "btn btn-outline-dark" %>
        <% if !task.status.eql?("Started")%>
          <%= button_to "Start", start_project_task_path(@project, task), method: :patch, class: "btn btn-outline-success" %>
        <% else %>
          <%= button_to "Finish", finish_project_task_path(@project, task), method: :patch, class: "btn btn-outline-success" %>
        <% end %>
        <%= button_to "Destroy", project_task_path(@project, task), method: :delete, class: "btn btn-outline-danger" %>
      </div>
    </div>
  </div>

app/views/tasks/edit.html.erb
<p style="color: green"><%= notice %></p>
<div class="container my-4 text-center">
  <h1>Editing task</h1>
</div>
<nav class="navbar navbar-expand-lg justify-content-center", style="margin-bottom: 1rem;">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
        <li class="nav-item", style="padding-eft: 2rem; padding-right: 2rem;">
          <%= link_to "Back to tasks", project_tasks_path(@project), class: "nav-link active" %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <div class="row">
    <div class="col-7" style="margin: 0 auto 1rem;">
      <div class="card bg-body-tertiary">
        <%= render "form", task: @task %>
      </div>
    </div>
    <div class="col-5">
      <div class="card bg-body-tertiary" style="margin: 0 auto 1rem;">
        <div class="card-body">
          <h4>Owners</h4>
          <%= render 'developers_list', task: @task %>
          <%= render 'add_developer_form', project: @project, task: @task %>
        </div>
      </div>
      <div class="card bg-body-tertiary" style="margin: 0 auto 1rem;">
        <div class="card-body">
          <h4>Labels</h4>
          <%= render 'labels_list', task: @task %>
          <%= render 'add_label_form', task: @task %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container my-4 text-center">
  <h1>Tasks</h1>
</div>
<!-- Cards con i task da mostrare -->
<div id="tasks" class="container">
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg justify-content-center", style="margin-bottom: 1rem;">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
          <li class="nav-item", style="padding-eft: 2rem; padding-right: 2rem;">
            <%= link_to "Back to projects", projects_url(mode: "m"), class: "nav-link active" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <%= link_to "New task", new_project_task_path(@project), class: "btn btn-primary" %>
  <div class="row" style="margin-top: 1rem;">
    <% @tasks.each do |task| %>
      <div class="col-4">
        <%= render partial: "task", locals: {task: task, view_context: 'index'}  %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container my-4 text-center">
  <h1>New Task</h1>
</div>

<nav class="navbar navbar-expand-lg justify-content-center", style="margin-bottom: 1rem;">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
        <li class="nav-item", style="padding-eft: 2rem; padding-right: 2rem;">
          <%= link_to "Back to tasks", project_tasks_path(@project), class: "nav-link active" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <div class="card bg-body-tertiary" style="width: 33rem; margin: 0 auto 1rem;">
    <%= render "form", task: @task %>
  </div>
</div>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>
<!-- Navbar -->
<nav class="navbar navbar-expand-lg justify-content-center", style="margin-bottom: 1rem;">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
        <li class="nav-item", style="padding-eft: 2rem; padding-right: 2rem;">
          <%= link_to "Back to tasks", project_tasks_path(@project), class: "nav-link active" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <div class="card bg-body-tertiary" style="margin: 0 auto;">
    <%= render partial: "task", locals: { task: @task, view_context: 'show' } %>
  </div>
</div>