config/routes.rb
Rails.application.routes.draw do
  # Devise for developers
  devise_for :developers, controllers: {registrations: "developers/registrations"}

  # Root route
  root to: "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  # Resources
  resources :labels
  resources :developer_projects
  resources :notifications

  # Projects
  resources :projects do
    resources :tasks do
      member do
        patch "start"
        patch "finish"
      end
    end
    member do
      patch "cancel"
      patch "start"
      patch "finish"
    end
  end

  # Tasks
  resources :tasks do
    member do
      post "add_label"
      delete "remove_label"
      post "add_developer"
      delete "remove_developer"
    end
  end
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :tasks_labels, dependent: :destroy
  has_many :tasks, through: :tasks_labels

  validates :name,
    presence: true

  scope :recent, ->(*args) {
    where("created_at > ?",
      (args.first || 2.weeks.ago))
  }
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: %i[show edit update destroy]

  # GET /labels or /labels.json
  def index
    @labels = Label.all
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels or /labels.json
  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save
        format.html { redirect_to labels_url, notice: "Label was successfully created." }
        format.json { render :index, status: :created, location: @label }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1 or /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to labels_url, notice: "Label was successfully updated." }
        format.json { render :index, status: :ok, location: @label }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1 or /labels/1.json
  def destroy
    @label.destroy

    respond_to do |format|
      format.html { redirect_to labels_url, notice: "Label was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_label
    @label = Label.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def label_params
    params.require(:label).permit(:name)
  end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_form.html.erb
<%= form_with(model: label) do |form| %>
  <% if label.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(label.errors.count, "error") %> prohibited this label from being saved:</h2>
      <ul>
        <% label.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row mb-2">
    <%= form.label :name, "Name*", class: "col-sm-2 col-form-label" %>
    <div class="col-sm">
      <%= form.text_field :name, class: "form-control", required: true %>
    </div>
  </div>
  <div class="d-flex justify-content-between">
    <%= link_to "Cancel", labels_path, class: "btn btn-danger" %>
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/labels/_label.html.erb
<div id="<%= dom_id label %>", class="card" style="width: 18rem; margin-bottom: 1rem;">
  <div class="card-header">
    <h4>
      <%= label.name %>
    </h4>
  </div>
  <div class="card-body">
    <div class="d-flex justify-content-between">
      <%= link_to "Edit", edit_label_path(label), class: "btn btn-outline-primary" %>
      <%= button_to "Destroy", label, method: :delete, class: "btn btn-outline-danger" %>
    </div>
  </div>
</div>

app/views/labels/edit.html.erb
<div class="container my-4 text-center">
  <h1>Editing label</h1>
</div>
<div class="container">
  <div class="card bg-body-tertiary", style="width: 33rem; margin: 0 auto 1rem;">
    <div class="card-body">
      <%= render "form", label: @label %>
    </div>
  </div>
</div>

app/views/labels/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container my-4 text-center">
  <h1>Labels</h1>
</div>
<!-- Navbar -->
<nav class="navbar navbar-expand-lg justify-content-center", style="margin-bottom: 1rem;">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
        <li class="nav-item", style="padding-eft: 2rem; padding-right: 2rem;">
          <%= link_to "Back to projects", projects_url(mode: "m"), class: "nav-link active" %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div id="labels" class="container">
  <%= link_to "New label", new_label_path, class: "btn btn-primary" %>
  <div class="row" style="margin-top: 1rem;">
    <% @labels.each do |label| %>
      <div class="col">
        <%= render label %>
      </div>
    <% end %>
  </div>
</div>

app/views/labels/new.html.erb
<div class="container my-4 text-center">
  <h1>New label</h1>
</div>
<div class="container">
  <div class="card bg-body-tertiary", style="width: 33rem; margin: 0 auto 1rem;">
    <div class="card-body">
      <%= render "form", label: @label %>
    </div>
  </div>
</div>