config/routes.rb
Rails.application.routes.draw do
  # Devise for developers
  devise_for :developers, controllers: {registrations: "developers/registrations"}

  # Root route
  root to: "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  # Resources
  resources :labels
  resources :developer_projects
  resources :notifications

  # Projects
  resources :projects do
    resources :tasks do
      member do
        patch "start"
        patch "finish"
      end
    end
    member do
      patch "cancel"
      patch "start"
      patch "finish"
    end
  end

  # Tasks
  resources :tasks do
    member do
      post "add_label"
      delete "remove_label"
      post "add_developer"
      delete "remove_developer"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render
  end
end

app/views/home/index.html.erb
<% if developer_signed_in? %> 
  <div class="container my-5 text-center">
    <p> Welcome <%= current_developer.name %> </p> 
    <%= link_to "See your projects", projects_url(mode: "m"), class: "btn btn-primary my-5", role: "button" %>
    <%= button_to "Sign out", destroy_developer_session_path, method: :delete, class: "btn btn-danger" %>
  </div>
  
<% else %>
  <div class="container my-5 text-center">
    <h1>Manage yours projects</h1>
    <p>Progetto per il Laboratorio di Industria 4.0 che ha l'obiettivo di simulare un sistema di gestione di progetti informatici. Ogni progetto è composto da vari task caratterizzati da labels e possiede diversi collaboratori oltre che a un project manager</p>
    <%= link_to "Sign in", new_developer_session_url, class: "btn btn-primary my-5", role: "button" %>
  </div>
<% end %>