config/routes.rb
Rails.application.routes.draw do
  # Devise for developers
  devise_for :developers, controllers: {registrations: "developers/registrations"}

  # Root route
  root to: "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  # Resources
  resources :labels
  resources :developer_projects
  resources :notifications

  # Projects
  resources :projects do
    resources :tasks do
      member do
        patch "start"
        patch "finish"
      end
    end
    member do
      patch "cancel"
      patch "start"
      patch "finish"
    end
  end

  # Tasks
  resources :tasks do
    member do
      post "add_label"
      delete "remove_label"
      post "add_developer"
      delete "remove_developer"
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :developer
  has_many :tasks
  has_many :developer_projects
  has_many :developers, through: :developer_projects

  validates :title,
    presence: true
  validates :deadline,
    presence: true
  validates :customer,
    presence: true,
    format: {with: /\A[a-zA-Z\s]+\z/, message: "only allows letters and spaces"}
  validates :description,
    presence: true
  validates :status,
    presence: true,
    inclusion: {in: %w[Unstarted Started Finished Cancelled], message: "%{value} is not a valid status"}
  validate :start_date_cannot_be_in_the_past, :end_date_cannot_be_in_the_past, :deadline_cannot_be_in_the_past, :start_date_has_to_be_smaller_than_deadline, :end_date_has_to_be_greater_than_start_date

  def start_date_cannot_be_in_the_past
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "can't be in the past")
    end
  end

  def end_date_cannot_be_in_the_past
    if end_date.present? && end_date < Date.today
      errors.add(:end_date, "can't be in the past")
    end
  end

  def deadline_cannot_be_in_the_past
    if deadline.present? && deadline < Date.today
      errors.add(:deadline, "can't be in the past")
    end
  end

  def start_date_has_to_be_smaller_than_deadline
    if start_date.present? && deadline.present? && deadline < start_date
      errors.add(:start_date, "can't be after deadline")
    end
  end

  def end_date_has_to_be_greater_than_start_date
    if start_date.present? && end_date.present? && start_date > end_date
      errors.add(:end_date, "can't be earlier than start date")
    end
  end

  scope :unstarted, -> { where(status: "Unstarted") }
  scope :started, -> { where(status: "Started") }
  scope :finished, -> { where(status: "Finished") }
  scope :cancelled, -> { where(status: "Cancelled") }

  scope :recent, ->(*args) {
                   where("start_date > ?",
                     (args.first || 2.weeks.ago))
                 }

  scope :overdue, -> { where(status: "Started").where("deadline < ?", Date.today) }

  scope :owner, ->(*args) { where("developer_id = ?", args.first) }
  scope :collaborate, ->(*args) { Project.joins(:developer_projects).where("developer_projects.developer_id = ?", args.first) }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy start finish]

  # GET /projects or /projects.json
  # GET /projects?mode=m
  # GET /projects?mode=c
  def index
    if params[:mode].eql? "m"
      @projects = Project.owner(current_developer.id)
    end
    if params[:mode].eql? "c"
      @projects = Project.collaborate(current_developer.id)
    end
  end

  # GET /projects/1 or /projects/1.json
  def show
    @developers = Developer.collaborators(params[:id])
    @developer_projects = DeveloperProject.where(project_id: params[:id])
    @developer_project = DeveloperProject.new
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    developer = Developer.find(current_developer.id)

    @project.developer = developer
    @developer_project = DeveloperProject.new(developer: developer, project: @project, email: developer.email, status: "Active")

    respond_to do |format|
      if @project.save
        if @developer_project.save
          format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
          format.json { render :show, status: :created, location: @project }
        else
          format.html { render :new, alert: "Unprocessable entity. Errors: #{@developer_project.errors.full_messages.join(", ")}", status: :unprocessable_entity }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new, alert: "Unprocessable entity. Errors: #{@project.errors.full_messages.join(", ")}", status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def cancel
    respond_to do |format|
      @project = Project.find(params[:id])
      if @project.update(status: "Cancelled")
        format.html { redirect_to project_url(@project), notice: "Project was successfully Cancelled." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def start
    respond_to do |format|
      if @project.update(status: "Started", start_date: Date.today, end_date: nil)
        format.html { redirect_to project_url(@project), notice: "Project was successfully started." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :show, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def finish
    respond_to do |format|
      if @project.update(status: "Finished", end_date: Date.today)
        @project.developer_projects.each do |developer_project|
          developer_project.developer.notifications.create(text: "The project #{@project.title} has been finished.", read: false)
        end
        format.html { redirect_to project_url(@project), notice: "Project was successfully finished." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :show, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:title, :deadline, :customer, :description, :start_date, :end_date, :status)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row mb-2">
    <%= form.label :title, "Title *", class: "col-sm-4 col-form-label"%>
    <div class="col-sm-8">
      <%= form.text_field :title, class: "form-control", required: true %>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label :deadline, "Deadline *", class: "col-sm-4 col-form-label"%>
    <div class="col-sm-8">
      <%= form.date_field :deadline, class: "form-control", required: true %>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label :customer, "Customer *", class: "col-sm-4 col-form-label"%>
    <div class="col-sm-8">
      <%= form.text_field :customer, class: "form-control", required: true %>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label :description, "Description *", class: "col-sm-4 col-form-label"%>
    <div class="col-sm-8">
      <%= form.text_area :description, class: "form-control", required: true %>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label :status, "Status *", class: "col-sm-4 col-form-label"%>
    <div class="col-sm-8">
      <%= form.select :status, [['Please, select an option', nil], 'Unstarted', 'Started', 'Finished'], {}, class: "form-select", required: true %>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label :start_date, class: "col-sm-4 col-form-label"%>
    <div class="col-sm-8">
      <%= form.date_field :start_date, class: "form-control" %>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label :end_date, class: "col-sm-4 col-form-label"%>
    <div class="col-sm-8">
      <%= form.date_field :end_date, class: "form-control" %>
    </div>
  </div>
  
  <div class="d-flex justify-content-between">
      <% if project.persisted? %>
        <%= link_to "Cancel", project, class: "btn btn-danger" %>
      <% else %>
        <%= link_to "Back to projects", projects_url(mode: "m"), class: "btn btn-danger" %>
      <% end %>
      <%= form.submit class: "btn btn-primary" %>
  <% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>", class="card" style="margin-bottom: 1rem;">
  <div class="card-header">
    <h4>
      <%= project.title %>
    </h4>
  </div>

  <div class="card-body">
    <p class="card-text">
      <strong>Deadline:</strong>
      <%= project.deadline %>
    </p>

    <p class="card-text">
      <strong>Customer:</strong>
      <%= project.customer %>
    </p>

    <p class="card-text">
      <strong>Description:</strong>
      <%= project.description %>
    </p>

    <p class="card-text">
      <strong>Status:</strong>
      <%= project.status %>
    </p>

    <p class="card-text">
      <strong>Start date:</strong>
      <%= project.start_date %>
    </p>

    <p class="card-text">
      <strong>End date:</strong>
      <%= project.end_date %>
    </p>

    <%= link_to "Show this project", project, class: "btn btn-primary" %>

  </div>

</div>

app/views/projects/edit.html.erb
<!-- Benvenuto -->
<p style="margin-left: 1%; margin-top: 1%"> Welcome <%= current_developer.name %> </p>

<!-- Titolo -->
<div class="container my-4 text-center">
  <h1>Editing project</h1>
</div>

<!-- Progetto da editare-->
<div class="container">
  <div class="card bg-body-tertiary" style="width: 33rem; margin: 0 auto 1rem;">
    <div class="card-body">
      <%= render "form", project: @project %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<!-- Bnevenuto -->
<p style="margin-left: 1%; margin-top: 1%"> Welcome <%= current_developer.name %> </p>

<!-- Titolo -->
<div class="container my-4 text-center">
  <% if(params[:mode].eql? "m") %> 
    <h1>Projects you manage</h1>
  <% else %>
    <h1>Projects in which you collaborate</h1>
  <% end %> 
</div>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg justify-content-center", style="margin-bottom: 1rem;">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
        <li class="nav-item", style="padding-eft: 2rem; padding-right: 2rem;">
          <% if(params[:mode].eql? "m")%>
            <%= link_to "Show Projects you collaborate for", projects_url(mode: "c"), class: "nav-link active"%> 
          <% end%>
          <% if(params[:mode].eql? "c")%>
              <%= link_to "Show Projects you manage", projects_url(mode: "m"), class: "nav-link active"%> 
          <% end%>
        </li>
        <li>
          <%= link_to "Show Labels", labels_path, class: "nav-link active" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<!-- Cards con i progetti da mostrare -->
<div id="projects" class="container">
<%= link_to "New project", new_project_path, class: "btn btn-primary" %>
  <div class="row", style="margin-top: 1rem;">
    <% @projects.each do |project| %>
      <div class="col-4">
        <%= render project %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<!-- Benvenuto -->
<p style="margin-left: 1%; margin-top: 1%"> Welcome <%= current_developer.name %> </p>

<!-- Titolo -->
<div class="container my-4 text-center">
  <h1>New project</h1>
</div>

<!-- Card per la form di creazione del nuovo progetto -->
<div class="container">
  <div class="card bg-body-tertiary" style="width: 33rem; margin: 0 auto 1rem;">
    <div class="card-body">
      <%= render "form", project: @project %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<!-- Benvenuto -->
<p style="margin-left: 1%; margin-top: 1%"> Welcome <%= current_developer.name %> </p>

<!-- Titolo -->
<div class="container my-4 text-center">
  <h1><%= @project.title %></h1>
</div>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg justify-content-center", style="margin-bottom: 1rem;">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
        <li class="nav-item", style="padding-eft: 2rem; padding-right: 2rem;">
          <%= link_to "Back to projects", projects_url(mode: "m"), class: "nav-link active" %>
        </li>
        <li class="nav-item", style="padding-eft: 2rem; padding-right: 2rem;">
          <%= link_to "Show tasks", project_tasks_path(@project), class: "nav-link active" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container", style="margin-bottom: 1rem;">

  <!-- Card di sinistra con le informazioni del progetto -->
  <div class="row align-items-md-stretch">
    <div class="col-md-6">
      <div class="h-100 p-5 text-bg-dark rounded-3">
        <h2>Project details</h2>

        <p class="card-text">
          <strong>Deadline:</strong>
          <%= @project.deadline %>
        </p>

        <p class="card-text">
          <strong>Customer:</strong>
          <%= @project.customer %>
        </p>

        <p class="card-text">
          <strong>Description:</strong>
          <%= @project.description %>
        </p>

        <p class="card-text">
          <strong>Status:</strong>
          <% if @project.status == "Cancelled" %>
            <span style="color: red;"><%= @project.status %></span>
          <% else %>
            <%= @project.status %>
          <% end %>
        </p>

        <p class="card-text">
          <strong>Start date:</strong>
          <%= @project.start_date %>
        </p>

        <p class="card-text">
          <strong>End date:</strong>
          <%= @project.end_date %>
        </p>

        <% if !@project.status.eql?("Cancelled") && @project.developer.email.eql?(current_developer.email) %>
          <div class="row row-cols-auto">
            <div class="col">
              <%= button_to "Edit", edit_project_path(@project), method: :get, class: "btn btn-outline-light" %>
            </div>
            <div class="col">
              <% if !@project.status.eql?("Started")%>
                <%= button_to 'Start', start_project_path(@project), method: :patch, class: "btn btn-outline-success" %>
              <% else %>
                <%= button_to 'Finish', finish_project_path(@project), method: :patch, class: "btn btn-outline-success" %>
              <% end %>
            </div>
            <div class="col">
              <%= button_to 'Delete', cancel_project_path(@project), method: :patch, data: { confirm: 'Sei sicuro?' }, class: "btn btn-outline-danger" %>
            </div>
          </div>
        <%end%>
      </div>
    </div>

    <!-- Card di destra per i collaboratori -->
    <div class="col-md-6">
      <div class="h-100 p-5 bg-body-tertiary border rounded-3">
        <h2>Collaborators</h2>

        <!-- FORM PER CAMBIARE LO STATO DI UN COLLABORATORE -->
        <% @developer_projects.each do |developer_project| %>
          <%= form_with(model: developer_project) do |form| %>
            <div>
              <p>
                <strong>Email:</strong>
                <%= developer_project.email %>
                <% if !@project.status.eql?("Finished") && !@project.status.eql?("Cancelled") && @project.developer.email.eql?(current_developer.email)%>
                  <br>
                  <div class="row">
                    <div class="col-sm-4">
                      <strong>Status:</strong>
                      <%= developer_project.status %>
                    </div>
                    <div class="col-sm-8">
                      <%= hidden_field_tag "project_id", @project.id %>
                      <%= hidden_field_tag "developer_id", developer_project.developer_id %>
                      <%= hidden_field_tag "email", developer_project.email %>
                      <%= select_tag "status", options_for_select([['Select a status', nil], "Active", "Inactive" ]), class: "form-select"%>
                    </div>
                  </div>
                  <%= form.submit "Change status collaborator", class: "btn btn-outline-secondary mt-3"%>
                <% end %>
              </p>
            </div>
          <% end %>
          
        <% end %>

        <% if !@project.status.eql?("Finished") && !@project.status.eql?("Cancelled") && @project.developer.email.eql?(current_developer.email) %>
          <!-- FORM PER AGGIUNGERE UN COLLABORATORE -->
          <h5>Add a collaborator to this project</h5>
          <%= form_for @developer_project do |form| %>
            <div class="row">
              <div class="col-sm-4">
                <%= form.label :email, style: "display: block" %>
              </div>
              <div class="col-sm-8">
                <%= text_field_tag "email", nil, class: "form-control"%>
                <%= hidden_field_tag "project_id", @project.id %>
              </div>
            </div>

            <div>
              <%= form.submit "Add collaborator", class: "btn btn-outline-secondary mt-3"%>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>